version: '3'

services:
  web:
    build: ./web
    ports:
      - 8080:8080
    volumes:
      - ./web:/app
    stdin_open: true
    tty: true
    command: /bin/sh

  api:
    build: ./api
    ports:
      - 8888:8888
    volumes:
      - ./api:/go/src/api
    depends_on:
      - db
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DB: todo
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./db/conf/conf.d:/etc/mysql/conf.d:rw
      - ./dump:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
